<!-- 

  ..... error handling in .then promise consuming syntax is by using .catch(error) method.... which AUTOMATICALLY catches the NETWORK ERRORS.... but have to define ERRORS manually for REJECTED PROMISES...

  .... in ASYNC AWAIT promise consuming syntax.... error handling is achieved using TRY CATCH BLOCK INSIDE the ASYNC FUNCTION 

    ** TRY CATCH block is an INBUILD FEATURE of JS and not part of ASYNC AWAIT 

        - syntax of SIMPLE TRY CATCH 

            try {
              codes whit manual error thrown with

                throw new Error('<message>')
            } catch (error) {
              console.log(error.message)
            }

            ** try catch will RUN the codes inside it EVEN if it ENCOUNTERS an ERROR

            ** CATCH block will catch the error thrown inside the try block and is commonly used to log it inside the console 

              ** catch block comes with an inbuild ERROR argument with it.... <ERROR>.message will display the message thrown by the error 
        
        **** TRY WON'T WORK without a CATCH BLOCK

  ** using TRY CATCH WITH ASYNC WAIT for ERROR HANDLING 

        async function <function name> () {
          
          try {
            async codes with manual error defining using 

              throw new Error('<message>')
          } catch (error) {
            console.log(error.message)
          }
        }

 -->

<!-- practice 

  ** use ASYNC AWAIT.... with TRY CATCH BLOCKs to 

    - do a call to this endpoint: https://jsonplaceholder.typicode.com/posts/101

    - the endpoint will reject because the endpoint only has 100 posts to display

    - handle the rejection.... by throwing an error.... using the <response>.ok flag.... 

    - to show the error.... use alert box to display error message AND THE STATUS CODE

    

  -->

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <script>
    const fetch_async_function = async () => {

      try {
        const response = await fetch('https://jsonplaceholder.typicode.com/posts/101')

        const data = await response.json()

        if (response.ok == false) {
          throw new Error(`only has 100 posts: error code ${response.status}`)
        }

        console.log(data)
      } catch (error) {
        console.error(error.message)
        alert(error.message)
      }
    }

    fetch_async_function()
  </script>
</body>

</html>